services:
  db:
    deploy:
      replicas: 1
    container_name: postgres
    image: postgres:16.4-alpine3.20
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:error}
      POSTGRES_DB: ${POSTGRES_DB?:error}
      DATABASE_URL: ${DATABASE_URL?:error}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: