[package]
name = "halfmill-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
halfmill-queue.workspace = true
halfmill-worker.workspace = true
halfmill-common.workspace = true
anyhow.workspace = true