[package]
name = "halfmill-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
sqlx.workspace = true
serde.workspace = true