[package]
name = "halfmill-worker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
tokio.workspace = true
axum.workspace = true
halfmill-common.workspace = true
serde.workspace = true